version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: xflair/dev:latest
    ports:
      - '3000:3000'
    environment:
      - mode=development
      - SERVICE_HOST=host.docker.internal
    env_file:
      - .env
    depends_on:
      - model

  model:
    build:
      context: ./Models/Tensorflow
      dockerfile: Dockerfile
    image: xflair/tensorflow:latest
    ports:
      - '5000:5000'
    env_file:
      - ./Models/TensorFlow/.env
    entrypoint: /TensorFlow/start/start.sh
