version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: xflair/dev:latest
    ports:
      - '3000:3000'
    depends_on:
      - model

  model:
    build:
      context: ./ModelContainerNew
      dockerfile: Dockerfile
    image: xflair/modelnew:latest
    ports:
      - '5000:5000'
      - '6006:6006'
    env_file:
      - ./ModelContainerNew/.env
    volumes:
      - ./ModelContainerNew/model/logs:/model_container/model/logs
    entrypoint: /model_container/start/start.sh